<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/cauhinh/">Cấu hình hệ thống</a>
        </li>
</ul>
</div>
<div class="row-fluid sortable">
<div class="box span12">
    <div class="box-header well" data-original-title>
						<h2><i class="icon-edit"></i> Form Nhập Liệu</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
    </div>
<?php
foreach ($this->books as $val)
{
     $banner = thay_the_fckeditor($val['banner']);
     $footer = thay_the_fckeditor($val['footer']);
    ?>
   
  
 
  <div class="box-content">
  
<form action='' method='post' enctype='multipart/form-data' name='tt_mh' id='tt_mh' class="form-horizontal"  >
   
          
         <div class="control-group">
                  <label class="control-label" for="typeahead">Title </label>
                  <div class="controls">
                    <input name="tieude" type="text" class="span6 typeahead" id="typeahead" value="<?php  echo $this->escape($val['tieude']); ?>" data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
	</div>
                
                
        <div class="control-group">
                  <label class="control-label" for="typeahead">Description </label>
                  <div class="controls">
                   
                     <textarea name="dis" cols="70" rows="10" class="span6 typeahead" id="typeahead" ><?php  echo $this->escape($val['dis']); ?></textarea>
               
                  </div>
	</div>
            
           
           
                     
                     
         <div class="control-group">
                  <label class="control-label" for="typeahead">Keywords </label>
                  <div class="controls">
                   
                     <textarea name="key" cols="70" rows="10" class="span6 typeahead" id="typeahead" ><?php  echo $this->escape($val['key']); ?></textarea>
               
                  </div>
	</div>
    
        <div class="control-group" id="content">
              <label class="control-label" for="textarea2">Banner</label>
              <div class="controls">
                    <div id="div_vn_afc">
              <script type="text/javascript">
                    var oFCKeditor = new FCKeditor('banner');
                    oFCKeditor.BasePath = "<?php echo $this->baseUrl(); ?>/fckeditor/";
                    oFCKeditor.Width	= 800 ;
                    oFCKeditor.Height	= 300 ;
                    oFCKeditor.Value="<?php echo $banner; ?>";
                    oFCKeditor.Config["EnterMode"]		= "br" ;
                    oFCKeditor.Create();
                    document.getElementById('xEnter').value = "br" ;
                    //document.getElementById("noidung").value=jljl;
            </script>
            </div>
              </div>
	</div>
        <div class="control-group" id="content">
              <label class="control-label" for="textarea2">Footer</label>
              <div class="controls">
                    <div id="div_vn_afc">
              <script type="text/javascript">
                    var oFCKeditor = new FCKeditor('footer');
                    oFCKeditor.BasePath = "<?php echo $this->baseUrl(); ?>/fckeditor/";
                    oFCKeditor.Width	= 800 ;
                    oFCKeditor.Height	= 300 ;
                    oFCKeditor.Value="<?php echo $footer; ?>";
                    oFCKeditor.Config["EnterMode"]		= "br" ;
                    oFCKeditor.Create();
                    document.getElementById('xEnter').value = "br" ;
                    //document.getElementById("noidung").value=jljl;
            </script>
            </div>
              </div>
	</div>
             
            
    
            <div class="form-actions">
                  <button type="submit" class="btn btn-primary"  >Save changes</button>
                  <button type="reset" class="btn">Cancel</button>
            </div>
            
    
      </form>
  </div>
<?php
    }
?>

</div></div>                    