
<div style="float: left">
<?php $page = new Default_Model_Page(); $hotline = $page->page_3(62); 
 foreach ($hotline as $value) {
    echo $value['content'];
}
?>
</div>

<div class="search">
    
    <form>
        <div class="linkcart">
		<a data-index="2" rel="nofollow" href="http://sakurabeauty.com.vn/gio-hang"></a>
		
			</div>
        <input type="text" id="key" class="input" />
        <input type="submit"  value="" id="search" class="sub"/>
    </form>
</div>