<?php $base=$this->baseurl();  ?>
<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/template/css/hoverex-all.css" />
<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/template/css/templates.css" />
<script type="text/javascript" src="<?= $this->baseUrl(); ?>/template/js/jquery.hoverex.js"></script>

<div class="title1">
    <h3> Thông tin chung</h3>
</div>
<?php foreach ($this->book as $value) {
    $title=$value['title'];
     $images=$value['images'];
      $members=$value['members'];
      $tv = new Zend_Session_Namespace('members');
      $tv->members=$members;
       $views=$value['views'];
       $count=$views+1;
       
       $mystring = $value['date'];
        $findme   = '-';
        $pos = strpos($mystring, $findme);
        if ($pos === false) {
             $date=gmdate("d-m-Y", $value['date'] + 7*3600);
        } else {
            $date	=$value['date'];
        }
       $id=$value['id'];
       $district_id=$value['district_id'];
        $menu_id=$value['menu_id'];
        $content=$value['content'];
         $code=$value['code'];
        $price=$value['price'];
        $giaban=number_format($price, 0 , '.', '.');
        
        if($giaban<>0){$gia="$giaban"." VNĐ";}
	else{$gia="Vui lòng liên hệ";}
        
        $state=$value['state'];
        if ($state==""){ $trangthai="Đang cập nhật";}  else { $trangthai=$state;}
        $sales=$value['sales'];
        if ($sales==""){ $khuyenmai="0%";}  else { $khuyenmai=$sales;}
        $made_in=$value['made_in'];
         if ($made_in==""){ $xuatxu="Đang cập nhật";}  else { $xuatxu=$made_in;}
        
        $vi=new Default_Model_Page();
        $vi->update_views($count, $id);
        
          $ctrol=  Zend_Controller_Front::getInstance()->getRequest()->getParam('title');
 ?>
<div class="sanpham">
    <h2><a href="<?= $base ?>/chi-tiet/<?= $ctrol ?>-<?= $id ?>.html" title="" > <?= $title ?></a></h2>
    <div class="thongtin1">
        <img src="<?= $base; ?>/Upload/<?= $images ?>" height="100" width="100" title="<?= $title; ?>" alt="<?= $title ?>"  border="0" style="float:left">
    </div>
    
    <div class="thongtin2">
       
        <ul class="le">
            <li class="cp"><b>Mã SP:</b> </li>
            <li class="cr"> 
                <?php $dtr=new Default_Model_Page(); echo $code;  ?>
            </li>
        </ul>
        <div class="clear"></div>
        <ul class="chan">
            <li class="cp"><b>Danh mục :</b> </li>
            <li class="cr"> <?php $dtr->menu($menu_id); ?></li>
        </ul>
        <div class="clear"></div>
        <ul class="le">
            <li class="cp"><b>Giá bán:</b> </li>
            <li class="cr"> <?= $gia ?></li>
        </ul>
        <div class="clear"></div>
        <ul class="chan">
            <li class="cp"><b>Trạng thái:</b> </li>
            <li class="cr"> <?= $trangthai ?></li>
        </ul>
        <div class="clear"></div>
        <ul class="le">
            <li class="cp"><b>Xuất xứ:</b> </li>
            <li class="cr"> <?= $xuatxu ?></li>
        </ul>
        <div class="clear"></div>
        <ul class="chan">
            <li class="cp"><b>Khuyến mãi:</b> </li>
            <li class="cr"> <?= $khuyenmai ?></li>
        </ul>
        
        <div class="clear" style="height: 13px;"></div>
        
    </div>
    
    
        
<div class="clear"></div>

</div>


<div class="clear"></div>
<div class="title1">
    <h3> Đặc điểm chi tiết</h3>
</div>
    
 
<div class="sanpham">
  <?= $content ?>
<div class="clear"></div>

</div>


<div class="clear"></div>





<div class="clear"></div>
<div class="title1">
    <h3> Bình luận nhận xét</h3>
</div>
<div class="sanpham">
        <div class="fb-comments" data-href="<?= $base ?>/chi-tiet/<?= $ctrol ?>-<?= $id ?>.html" data-width="740" data-num-posts="10"></div>
<div class="clear"></div>

</div>




<?php } ?>
<div class="clear"></div>
<div class="title1">
    <h3> Sản phẩm khác</h3>
</div>

<div class="sanpham">
        <?php foreach ($this->bookk as $val) {
    $id=$val['id'];
        $title=$val['title'];
        $images=$val['images'];
         $mask = APPLICATION_PATH."/../Upload/$images"; 
        if (file_exists($mask)){
            $images=$val['images'];
        } else {
             $images="no-img.png";
        }
        $description	=$val['description'];
       $mystring = $val['date'];
        $findme   = '-';
        $pos = strpos($mystring, $findme);
        if ($pos === false) {
             $date=gmdate("d-m-Y", $val['date'] + 7*3600);
        } else {
            $date	=$val['date'];
        }
         $area	=$val['area'];
        if(strlen($description)>300)
        {       $new_gioihan=strpos($description," ",300);
                $new_chuoi = substr($description,0,$new_gioihan)."...";
        }
        else {  $new_chuoi= $description;
        }
         $price=$val['price'];
        $giaban=number_format($price, 0 , '.', '.');
        
        if($giaban<>0){$gia="$".$giaban;}
	else{$gia="$0";}
        $url=  khongdau($title);
        $link="$base/chi-tiet/$url-$id.html";
        $code=$val['code'];
     ?>
    <div class="product" align="left">           
        
        
        <div class="he-wrap tpl4">
            <div class="img_pro"><img src="<?= $base ?>/Upload/<?= $images ?>"  alt="<?= $title ?>" border="0" style="float:left;"></div>
            <div class="he-view">
                    <div class="bg">
                            <div class="a0" data-animate="fadeInUp"></div><div class="a1" data-animate="fadeInUp"></div><div class="a2" data-animate="fadeInUp"></div><div class="a3" data-animate="fadeInUp"></div><div class="a4" data-animate="fadeInUp"></div>
                    </div>
                    <div class="content">
                        <h3 class="info-title a3" data-animate="fadeInLeft" title="<?= $title ?>"><?= $title ?></h3>
                          
                            <a href="<?= $link ?>" class="more a5" data-animate="fadeInRight"  title="<?= $title ?>">View Detail</a>
                    </div>
            </div>
	</div>
        
        
 <div class="txt_pro" align="left">
	   		<div class="sp"><a href="<?= $link ?>" title="<?= $title ?>" > <?= $title ?> </a></div>
	   		<div class="code"><a href="<?= $link ?>" title="<?= $title ?>" > <?= $gia ?></a></div>
	   
	   
</div>
        
        	</div>
    
    
    <?php } ?>
<div class="clear"></div>

</div>



