<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/template/css/hoverex-all.css" />
<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/template/css/templates.css" />
<script type="text/javascript" src="<?= $this->baseUrl(); ?>/template/js/jquery.hoverex.js"></script>
<div class="title1">
    <h3> <?php foreach ($this->books as $value) {
        
         echo $value['title_category']." &Rrightarrow; ";
           //$id_ca=$value['id_category'];
       // $url_tt=  khongdau($value['title_category']);
        // echo "<a href=\"$base/category/$url_tt-$id_ca.html\">".$value['title_category']." &Rrightarrow; </a>";
   }  
  $id__=$this->id;
   $page = new Default_Model_Page();
   $title_1=$page->list_menu_title_1($id__) ;
   $ktmnc = $page->kiem_tra_menu_con($id__);
    if($ktmnc=="co")
    {
        foreach ($title_1 as $list_1) {
            $title_11=$list_1['title'];
            $parent_11=$list_1['parent_id'];
            $page_1= $page->list_menu_title_2($parent_11);
            foreach ($page_1 as $value_1) {
               $title_112=$value_1['title']; 
            }
            echo $title_112;
                echo " &Rrightarrow; ";
            echo $title_11;
        } 
    }
 else {
        foreach ($title_1 as $list_1) {
          echo  $title_11=$list_1['title'];
        }       
}
?></h3>
</div>
<div class="sanpham">
   <div class="row-fluid sortable">
<div class="">
   
    
    <div class="box-content">
    <?php 
    $base=$this->baseurl();
    
    foreach ($this->book as $val) {
        
         $id=$val['id'];
        $title=$val['title'];
        $images=$val['images'];
         $mask = APPLICATION_PATH."/../Upload/$images"; 
        if (file_exists($mask)){
            $images=$val['images'];
        } else {
             $images="no-img.png";
        }
        $description	=$val['description'];
       $mystring = $val['date'];
        $findme   = '-';
        $pos = strpos($mystring, $findme);
        if ($pos === false) {
             $date=gmdate("d-m-Y", $val['date'] + 7*3600);
        } else {
            $date	=$val['date'];
        }
         $area	=$val['area'];
        if(strlen($description)>300)
        {       $new_gioihan=strpos($description," ",300);
                $new_chuoi = substr($description,0,$new_gioihan)."...";
        }
        else {  $new_chuoi= $description;
        }
         $price=$val['price'];
        $giaban=number_format($price, 0 , '.', '.');
        
        if($giaban<>0){$gia="$".$giaban;}
	else{$gia="$0";}
        $url=  khongdau($title);
        $link="$base/chi-tiet/$url-$id.html";
        $code=$val['code'];
     ?>
    <div class="product" align="left">           
        
        
        <div class="he-wrap tpl4">
            <div class="img_pro"><img src="<?= $base ?>/Upload/<?= $images ?>"  alt="<?= $title ?>" border="0" style="float:left;"></div>
            <div class="he-view">
                    <div class="bg">
                            <div class="a0" data-animate="fadeInUp"></div><div class="a1" data-animate="fadeInUp"></div><div class="a2" data-animate="fadeInUp"></div><div class="a3" data-animate="fadeInUp"></div><div class="a4" data-animate="fadeInUp"></div>
                    </div>
                    <div class="content">
                        <h3 class="info-title a3" data-animate="fadeInLeft" title="<?= $title ?>"><?= $title ?></h3>
                          
                            <a href="<?= $link ?>" class="more a5" data-animate="fadeInRight"  title="<?= $title ?>">View Detail</a>
                    </div>
            </div>
	</div>
        
        
 <div class="txt_pro" align="left">
	   		<div class="sp"><a href="<?= $link ?>" title="<?= $title ?>" > <?= $title ?> </a></div>
	   		<div class="code"><a href="<?= $link ?>" title="<?= $title ?>" > <?= $gia ?></a></div>
	   
	   
</div>
        
        	</div>
    
    
    <?php } ?>
         <?php  

echo $this->paginationControl($this->book,  'Sliding', 'page/pagination_product.phtml');

   ?>   <div class="clear"></div>
    </div></div></div>
<div class="clear"></div>

</div>




