
				<div class="well nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li class="nav-header hidden-tablet">Main</li>
                                                <li ><a class="ajax-link" href="<?php echo $this->baseUrl(); ?>/admin/index/cauhinh/"><i class="icon-home"></i><span class="hidden-tablet"> Cấu hình hệ thống</span></a></li>
						<li><a class="ajax-link" href="<?php echo $this->baseUrl(); ?>/admin/page/listpages/"><i class="icon-eye-open"></i><span class="hidden-tablet"> Quản lý trang</span></a>
                                                   
                                                </li>
						<li style="display: none"><a class="ajax-link" href="<?php echo $this->baseUrl(); ?>/admin/product/listproducts"><i class="icon-edit"></i><span class="hidden-tablet"> Quản lý danh mục</span></a></li>
                                                <li style="display: none"><a class="ajax-link" href="<?php echo $this->baseUrl(); ?>/admin/product/listorder/"><i class="icon-align-justify"></i><span class="hidden-tablet"> Quản lý hóa đơn</span></a></li>
						
						<li><a class="ajax-link" href="<?php echo $this->baseUrl(); ?>/admin/index/contact/"><i class="icon-font"></i><span class="hidden-tablet"> Liên hệ</span></a></li>
						<li><a class="ajax-link" href="<?php echo $this->baseUrl(); ?>/admin/support/listsupport/"><i class="icon-picture"></i><span class="hidden-tablet"> Hỗ trợ trực tuyến</span></a></li>
						
						
						<li><a class="ajax-link" href="<?php echo $this->baseUrl(); ?>/admin/side/listside/"><i class="icon-calendar"></i><span class="hidden-tablet">Hình ảnh sildeshow </span></a></li>
						<li style="display: none"><a class="ajax-link" href="grid.html"><i class="icon-th"></i><span class="hidden-tablet"> Album ảnh</span></a></li>
                                                <li><a href="<?php echo $this->baseUrl(); ?>/admin/link/listlink/"><i class="icon-globe"></i><span class="hidden-tablet"> Liên kết website</span></a></li>
						<li><a class="ajax-link" href="<?php echo $this->baseUrl(); ?>/admin/user/listuser/"><i class="icon-folder-open"></i><span class="hidden-tablet"> Đăng nhập</span></a></li>
						
						<li style="display: none"><a class="ajax-link" href="<?php echo $this->baseUrl(); ?>/admin/product/listdistrict"><i class="icon-list-alt"></i><span class="hidden-tablet"> Khu vực đăng tin</span></a></li>
                                                <li><a href="javascript:void(0)"><i class="icon-star"></i><span class="hidden-tablet"> Icons</span></a></li>
						<li><a href="javascript:void(0)"><i class="icon-ban-circle"></i><span class="hidden-tablet"> Error Page</span></a></li>
						<li><a href="<?php echo $this->baseUrl("/admin/index/logout");?>"><i class="icon-lock"></i><span class="hidden-tablet"> Logout Page</span></a></li>
					</ul>
					<label id="for-is-ajax" class="hidden-tablet" for="is-ajax"><input id="is-ajax" type="checkbox" > Ajax on menu</label>
				</div><!--/.well -->